services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_mosalla
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - web
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.mosalla.rule=Host(`mosalla-zn.ir`)"
      - "traefik.http.routers.mosalla.entrypoints=websecure"
      - "traefik.http.routers.mosalla.tls=true"
      - "traefik.http.routers.mosalla.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mosalla.service=mosalla"

      - "traefik.http.routers.mosalla-www.rule=Host(`www.mosalla-zn.ir`)"
      - "traefik.http.routers.mosalla-www.entrypoints=websecure"
      - "traefik.http.routers.mosalla-www.tls=true"
      - "traefik.http.routers.mosalla-www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mosalla-www.middlewares=redirect-www-to-main"
      - "traefik.http.routers.mosalla-www.service=mosalla"

      - "traefik.http.services.mosalla.loadbalancer.server.port=3000"

      - "traefik.http.middlewares.redirect-www-to-main.redirectregex.regex=^https?://www\\.(.+)"
      - "traefik.http.middlewares.redirect-www-to-main.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.redirect-www-to-main.redirectregex.permanent=true"

networks:
  web:
    external: true
